version: "2"
linters:
  enable:
    - contextcheck
    - errcheck
    - exhaustive
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused
formatters:
  enable:
    - gofumpt
