version: "2"
linters:
  settings:
    staticcheck:
      checks:
        - all
        - '-ST1003' # should not use underscores in Go names
        - '-ST1016' # methods on the same type should have the same receiver name
  enable:
    - contextcheck
    - errcheck
    - exhaustive
    - misspell
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
