FROM docker.io/library/centos:7

RUN useradd cluster-image-registry-operator
USER cluster-image-registry-operator

COPY cluster-image-registry-operator /usr/bin
COPY deploy/image-references deploy/crd.yaml deploy/namespace.yaml deploy/operator.yaml deploy/rbac.yaml /manifests/

LABEL io.openshift.release.operator true
