// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenShiftDockerRegistry) DeepCopyInto(out *OpenShiftDockerRegistry) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenShiftDockerRegistry.
func (in *OpenShiftDockerRegistry) DeepCopy() *OpenShiftDockerRegistry {
	if in == nil {
		return nil
	}
	out := new(OpenShiftDockerRegistry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenShiftDockerRegistry) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenShiftDockerRegistryList) DeepCopyInto(out *OpenShiftDockerRegistryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenShiftDockerRegistry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenShiftDockerRegistryList.
func (in *OpenShiftDockerRegistryList) DeepCopy() *OpenShiftDockerRegistryList {
	if in == nil {
		return nil
	}
	out := new(OpenShiftDockerRegistryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenShiftDockerRegistryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenShiftDockerRegistrySpec) DeepCopyInto(out *OpenShiftDockerRegistrySpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenShiftDockerRegistrySpec.
func (in *OpenShiftDockerRegistrySpec) DeepCopy() *OpenShiftDockerRegistrySpec {
	if in == nil {
		return nil
	}
	out := new(OpenShiftDockerRegistrySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenShiftDockerRegistryStatus) DeepCopyInto(out *OpenShiftDockerRegistryStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenShiftDockerRegistryStatus.
func (in *OpenShiftDockerRegistryStatus) DeepCopy() *OpenShiftDockerRegistryStatus {
	if in == nil {
		return nil
	}
	out := new(OpenShiftDockerRegistryStatus)
	in.DeepCopyInto(out)
	return out
}
