---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: image-registry-operator
  namespace: openshift-image-registry
spec:
  endpoints:
  - targetPort: 60000
    interval: 60s
    scheme: https
    path: /metrics
    tlsConfig:
      caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
      serverName: image-registry-operator.openshift-image-registry.svc
  selector:
    name: image-registry-operator
