---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: image-registry-operator
  namespace: openshift-image-registry
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    capability.openshift.io/name: Registry
spec:
  endpoints:
  - targetPort: 60000
    interval: 60s
    scheme: https
    path: /metrics
    tlsConfig:
      caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
      serverName: image-registry-operator.openshift-image-registry.svc
  selector:
    matchLabels:
      name: image-registry-operator
