apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: openshift-image-registry-azure
  namespace: openshift-cloud-credential-operator
  annotations:
    capability.openshift.io/name: ImageRegistry+CloudCredential
    include.release.openshift.io/hypershift: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
spec:
  serviceAccountNames:
  - cluster-image-registry-operator
  - registry
  secretRef:
    name: installer-cloud-credentials
    namespace: openshift-image-registry
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AzureProviderSpec
    permissions:
      - Microsoft.Storage/storageAccounts/blobServices/read
      - Microsoft.Storage/storageAccounts/blobServices/containers/read
      - Microsoft.Storage/storageAccounts/blobServices/containers/write
      - Microsoft.Storage/storageAccounts/blobServices/containers/delete
      - Microsoft.Storage/storageAccounts/blobServices/generateUserDelegationKey/action
      - Microsoft.Storage/storageAccounts/read
      - Microsoft.Storage/storageAccounts/write
      - Microsoft.Storage/storageAccounts/delete
      - Microsoft.Storage/storageAccounts/listKeys/action
      - Microsoft.Resources/tags/write
      # the permissions below are only necessary when users request
      # the operator to configure a private storage account.
      - Microsoft.Network/privateEndpoints/write
      - Microsoft.Network/privateEndpoints/read
      - Microsoft.Network/privateEndpoints/privateDnsZoneGroups/write
      - Microsoft.Network/privateEndpoints/privateDnsZoneGroups/read
      - Microsoft.Network/privateDnsZones/read
      - Microsoft.Network/privateDnsZones/write
      - Microsoft.Network/privateDnsZones/join/action
      - Microsoft.Network/privateDnsZones/A/write
      - Microsoft.Network/privateDnsZones/virtualNetworkLinks/write
      - Microsoft.Network/privateDnsZones/virtualNetworkLinks/read
      - Microsoft.Network/networkInterfaces/read
      - Microsoft.Storage/storageAccounts/PrivateEndpointConnectionsApproval/action
      - Microsoft.Network/virtualNetworks/subnets/read
      - Microsoft.Network/virtualNetworks/subnets/join/action
      - Microsoft.Network/virtualNetworks/join/action
    dataPermissions:
      - Microsoft.Storage/storageAccounts/blobServices/containers/blobs/delete
      - Microsoft.Storage/storageAccounts/blobServices/containers/blobs/write
      - Microsoft.Storage/storageAccounts/blobServices/containers/blobs/read
      - Microsoft.Storage/storageAccounts/blobServices/containers/blobs/add/action
      - Microsoft.Storage/storageAccounts/blobServices/containers/blobs/move/action
