kind: List
apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: pruner
    namespace: openshift-image-registry--
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: cluster-image-registry-operator
    namespace: openshift-image-registry
