---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-ca
  namespace: openshift-image-registry
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    include.release.openshift.io/single-node-production-edge: "true"
