---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: image-registry-operator-tls
  labels:
    name: image-registry-operator
  name: image-registry-operator
  namespace: openshift-image-registry
spec:
  clusterIP: None
  ports:
  - port: 60000
    protocol: TCP
    targetPort: 60000
  selector:
    name: cluster-image-registry-operator
