---
apiVersion: v1
kind: ConfigMap
data:
  cli: quay.io/openshift/origin-cli:v4.0
  must-gather: quay.io/openshift/origin-must-gather:v4.0
metadata:
  annotations:
    capability.openshift.io/name: ImageRegistry
    include.release.openshift.io/hypershift: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
  name: platform-images-references
  namespace: openshift-image-registry
