apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: image-registry-rules
  namespace: openshift-image-registry
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
spec:
  groups:
  - name: imageregistry.operations.rules
    rules:
    - expr: |
        label_replace(
          label_replace(
            sum by (operation) (imageregistry_request_duration_seconds_count{operation="BlobStore.ServeBlob"}), "operation", "get", "operation", "(.+)"
          ), "resource_type", "blob", "resource_type", ""
        )
      record: imageregistry:operations_count:sum

    - expr: |
        label_replace(
          label_replace(
            sum by (operation) (imageregistry_request_duration_seconds_count{operation="BlobStore.Create"}), "operation", "create", "operation", "(.+)"
          ), "resource_type", "blob", "resource_type", ""
        )
      record: imageregistry:operations_count:sum

    - expr: |
        label_replace(
          label_replace(
            sum by (operation) (imageregistry_request_duration_seconds_count{operation="ManifestService.Get"}), "operation", "get", "operation", "(.+)"
          ), "resource_type", "manifest", "resource_type", ""
        )
      record: imageregistry:operations_count:sum

    - expr: |
        label_replace(
          label_replace(
            sum by (operation) (imageregistry_request_duration_seconds_count{operation="ManifestService.Put"}), "operation", "create", "operation", "(.+)"
          ), "resource_type", "manifest", "resource_type", ""
        )
      record: imageregistry:operations_count:sum
